# Generated by Django 3.2.23 on 2023-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLToAST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.CharField(max_length=10000)),
                ('ast', models.CharField(blank=True, max_length=10000, null=True)),
                ('modified_query', models.CharField(blank=True, max_length=10000, null=True)),
                ('hashed_values', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'API_SQLToAST',
            },
        ),
    ]
