version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "sh", "./start.sh" ]
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres_db
    env_file:
      - .env
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - web

volumes:
  postgres_data:
